services:
  postgres-db:
    image: postgres:15.4-alpine3.18 
    ports:
      - "5432:5432"
    env_file:
      - ./fastapi-server/.env
    volumes:
      - ./fastapi-server/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  # qdrant-db:
  #   image: qdrant/qdrant:latest
  #   ports:
  #     - "6333:6333"
  #     - "6334:6334"
  #   volumes:
  #     - ./qdrant-data:/qdrant/storage
  #     # restart: unless-stopped

